### ISSUE TITLE
导出到2007xlsx后打开提示在 xlsx中发现了不可读取的内容

### ISSUE THREAD

**Issue by zhujinhu21** [dotnetcore/NPOI#104]
导出到excel后，打开excel报在 xlsx中发现了不可读取的内容

![tim 20181031190543](https://user-images.githubusercontent.com/4327149/47784265-05d09000-dd40-11e8-94c8-04d4c4596155.png)

什么原因造成的

**Comment by ShiYuHe** [comment]
me too。Have you solved it？
