### ISSUE TITLE
CreateFont() produces problem in excel

### ISSUE THREAD

**Issue by fdendorfer** [dotnetcore/NPOI#109]
I'm trying to style cells using following code. The problem is, that when I open file.xlsx it shows a message saying: "We found a problem with some content in 'file.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.
After clicking Yes, this repair info opens (below the code) (error...xml at the bottom).
Now the file opens and a dot is displayed in the cell, but "Hi" is correctly in the formula bar. Also bold is applied to that cell.

The project is running on .NET core 2.2 and the NuGet Package NPOI v2.4.1 is installed. The Excel version is Microsoft Office Professional Plus 2016 with the latest updates.

Thanks for any help

```
using (var file = new FileStream(@"C:\temp\file.xlsx", FileMode.Create, FileAccess.ReadWrite))
{
  var wb = new XSSFWorkbook();
  var sh = wb.CreateSheet("test");
  var row = sh.CreateRow(0);
  var font = wb.CreateFont();
  font.IsBold = true;
  var style = wb.CreateCellStyle();
  style.SetFont(font);
  var cell = row.CreateCell(0);
  cell.SetCellValue("Hi");
  cell.CellStyle = style;
   
  wb.Write(file);
}
```
![image](https://user-images.githubusercontent.com/23694947/51118435-a814f580-1810-11e9-8f3b-b00672922abe.png)
![image](https://user-images.githubusercontent.com/23694947/51118599-0e9a1380-1811-11e9-8d5d-182759b210c6.png)

**Comment by gcastre** [comment]
Same here, even creating just an empty sheet is causing this problem.

**Comment by jCharebois** [comment]
I was running into this issue as well with workseet.createFont(). I found that either setting the font.FontHeight or font.FontHeightInPoints  after using createfont() corrected the problem.

i did use a workbook.GetFontAt(0).FontHeight to get the default font height.

**Comment by fdendorfer** [comment]
Thanks very much @jCharebois, it worked for me aswell. I still hope they will correct this in the future.
