### ISSUE TITLE
Office 2013保存的xlsx文件读取时候乱码，只有部分数字可以正确识别

### ISSUE THREAD

**Issue by Luoyingliang** [dotnetcore/NPOI#15]

**Comment by yuleyule66** [comment]
NPOI 马上会迁移到.net china foundation，然后将重新释放新版本。解决诸多bug。

**Comment by yuleyule66** [comment]
NPOI Standard 2.0 has been released, the github remove to https://github.com/dotnetcore/NPOI
you can reinstall NPOI with :
```
PM: Install-Packege DotNetCore.NPOI
```
