### ISSUE TITLE
SetAutoFilter throws ArgumentNullException

### ISSUE THREAD

**Issue by gfoidl** [dotnetcore/NPOI#17]
For instance
```c#
ISheet sheet = workBook.CreateSheet(sheetName) as XSSFSheet;
sheet.SetAutoFilter(new NPOI.SS.Util.CellRangeAddress(0, sheet.LastRowNum, 0, propertyNames.Length - 1));
```
results in
```
Value cannot be null.
Parameter name: stream
```

This worked on NPOI. Please have a look at this.

**Comment by yuleyule66** [comment]
@gfoidl  
Sorry , this is a bug during migration,  I have been fixed it. 
I'll release a new version tomorrow.

**Comment by yuleyule66** [comment]
@gfoidl 
v1.0.1 has been released.

**Comment by gfoidl** [comment]
Perfect! All my tests are passing.

Thx for the fast fix, ans sorry for late reply -- I was on a business trip.
