### ISSUE TITLE
Unable to add Formula of SUM(E1:E6)

### ISSUE THREAD

**Issue by Grandizer** [dotnetcore/NPOI#19]
I am trying to export data to Excel and a rather simple SUM(E1:E6) fails with the error 

> Value cannot be null. Parameter name: stream.

`IWorkbook workbook = new XSSFWorkbook();`
`ISheet sheet1 = workbook.CreateSheet("Project Time");`

`... Other numeric and textual cells fill in and work great`

`row = sheet1.CreateRow(RowIndex++);`

`var test = row.CreateCell(ColIndex++);`
`test.SetCellType(CellType.Formula);`
`test.SetCellFormula($"1 + 2 + 3 + 4 + 5 + 6"); // WORKS`
`test.SetCellFormula($"SUM(1 + 2 + 3 + 4 + 5 + 6)"); // FAILS`
`test.SetCellFormula($"SUM(E1:E6)"); // FAILS`
`test.SetCellFormula($"E1 + E2 + E3"); // FAILS`

`XSSFFormulaEvaluator.EvaluateAllFormulaCells(workbook);`
`workbook.Write(TheStream);`

So what is the trick to Formulas?

**Comment by yuleyule66** [comment]
What is your NPOI version?

**Comment by Grandizer** [comment]
The NuGet Package says 1.0.0.  I just noticed an update (Seeing that I downloaded it yesterday...) And there is a 1.0.1 that I will try in a moment.

**Comment by Grandizer** [comment]
The 1.0.1 package seems to do the trick!  Thank you @yuleyule66

**Comment by yuleyule66** [comment]
Not at all, thanks your feedback.

**Comment by xingwen1987** [comment]
请问杨总，现在可以使用 SetCellFormula($"SUM(E1:E6)") 的方式设置公式了吗？
