### ISSUE TITLE
is it possible for npoi to covert word to pdf

### ISSUE THREAD

**Issue by abramhum** [dotnetcore/NPOI#20]
Hi:

I have a question about if is possible for npoi to covert word to pdf.
I found there seems no other third-party free library can do that,
so I hope to know if npoi can do that, and how to do.
any instruction is highly appreciated, thanks a lot.

**Comment by yuleyule66** [comment]
The short answer is: No, currently (N)POI does not offer any functionality to export a PDF file. The library focuses on manipulating Microsoft Office documents directly, not on converting them to different formats.

There are a lot of other libraries and services out there that will solve this (I can personally recommend [Aspose.Words](https://github.com/aspose-words/Aspose.Words-for-.NET), but it should definitely be possible to find something cheaper out there that meets your requirements).

Answer from [https://stackoverflow.com/questions/34718667/exporting-doc-to-pdf-using-poi](https://stackoverflow.com/questions/34718667/exporting-doc-to-pdf-using-poi)

**Comment by abramhum** [comment]
Thanks a lot
