### ISSUE TITLE
Predefined type 'MarshalByRefObject' defined in multiple assemblies

### ISSUE THREAD

**Issue by bwegman** [dotnetcore/NPOI#21]
After adding the DotNetCore.NPOI library to a library targeting netstandard2.0 I get the following warning when building the project:

`CSC : warning CS1685: The predefined type 'MarshalByRefObject' is defined in multiple assemblies in the global alias; using definition from 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

The 'MarshalByRefObject' type seems to be defined both in `netstandard, Version=2.0.0.0` as well as in `System.Runtime, Version=4.2.0.0`.

My .csproj looks like:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNetCore.NPOI" Version="1.0.0" />
  </ItemGroup>
</Project>
```

Any idea what is causing this and how to resolve?

**Comment by bwegman** [comment]
This seems to be caused by the reference to `ZKWeb.System.Drawing` version 3.0.0.0. Upgrading that dependency to 4.0.0.0 resolves the warning. You can also include the ZKWeb.System.Drawing 4.0.0.0 reference in the library that is referencing `DotNetCore.NPOI`.

**Comment by yuleyule66** [comment]
Sorry, a little busy recently, I haven't had time to check the problem.
Thank you, I will check it later.

**Comment by bwegman** [comment]
No problem, just figured it out myself. My colleague @jenwu has upgraded the reference in this package (see https://github.com/jenwu/NPOI/tree/MarshalByRefObjectWarning) but did not manage to get the test suite running. Any tips to get those running?

**Comment by yuleyule66** [comment]
@bwegman  Pull the latest code, I have fixed the problem of unit testing.
I also upgrade ZKWeb.System.Drawing to 4.0.0 .
