### ISSUE TITLE
Read an excel file example

### ISSUE THREAD

**Issue by butsaty** [dotnetcore/NPOI#22]
Hi,
Could you provide an example how to read an existing excel file by rows?

**Comment by yuleyule66** [comment]
https://gist.github.com/yuleyule66/1e2c9bba2dba00337535a282f1a0c1eb

**Comment by CharlesOkwuagwu** [comment]
@yuleyule66 Please can you guide me in this scenario:

I have an existing excel file `template.xlsx`.  I make a copy of this file, and I want to write to the copy with new data retaining the formatting of the `template.xlsx` file.

My attempt

https://gist.github.com/CharlesOkwuagwu/a9a34647070b87a86a170875a8468ced

Thanks.
