### ISSUE TITLE
Can you please confirm if it work with .net core 2.0

### ISSUE THREAD

**Issue by naveedahmed1** [dotnetcore/NPOI#24]
Hi,

Can you please confirm if it works with .Net Core 2.0?

I tried installing it but its showing yellow warning in dependencies node in solution explorer tree.

**Comment by yuleyule66** [comment]
Can you upload a screenshot and show the warning content?

**Comment by naveedahmed1** [comment]
Seems to be working now, I uninstalled the package and installed again and it started working. There could have been an issue with nuget, since I also tried ical.net core and that wasn't working as well. And today both started working.
