### ISSUE TITLE
Setting HSSFColor via RGB Does Not Work

### ISSUE THREAD

**Issue by Grandizer** [dotnetcore/NPOI#25]
Hello,

With the following code, the 1st way of creating a color works but the two commented out ones do not.  Am I doing something wrong?

`IWorkbook workbook = new XSSFWorkbook();`
` `
`var UniversalStyle = workbook.CreateCellStyle();`
`UniversalStyle.FillForegroundColor = HSSFColor.Automatic.Index;`
`UniversalStyle.FillPattern = FillPattern.NoFill;`
` `
`UniversalFont = workbook.CreateFont();`
`UniversalFont.Color = HSSFColor.Blue.Index;`
`// UniversalFont.Color = new XSSFColor(new byte[3] { 65, 124, 153 }).Indexed;`
`// UniversalFont.Color = new XSSFColor(System.DrawingCore.Color.FromArgb(65, 124, 153)).Indexed;`
`UniversalStyle.SetFont(UniversalFont);`
` `
`IRow row = sheet1.CreateRow(RowIndex++);`
`ICell test = row.CreateCell(ColIndex++);`
`test.CellStyle = UniversalStyle;`
`test.SetCellType(CellType.String);`
`test.SetCellValue("This should be Blue-ish");`

**Comment by yuleyule66** [comment]
Each Microsoft Excel workbook has a palette of 56 colors that you can apply to cells, fonts, gridlines, graphic objects, and fills and lines in a chart.

see: 
http://dmcritchie.mvps.org/excel/colors.htm
https://msdn.microsoft.com/en-us/vba/excel-vba/articles/colorindex-property

In NPOI, the color index are from `0x8` to `0x40`

![image](https://user-images.githubusercontent.com/8205994/30242391-2667ea72-95c8-11e7-8fee-6d1688b48b9c.png)

**Comment by Grandizer** [comment]
Understood.  Thank you.

**Comment by diogoan** [comment]
Sorry for asking this here (I don't know if this is the proper place to ask questions), but there's no way to set a custom RGB color into an XSSFColor object? We are restricted to the 56 colors of default Excel palette?

**Comment by esreeves** [comment]
This seems to be more of a limitation of the library. You are able to set custom colors within excel why are you not able to do it with this library. Maybe this should be reopened and tagged as a feature request?
