### ISSUE TITLE
Convert excel to PDF (in a .NET Core project)

### ISSUE THREAD

**Issue by MaximCrabbe** [dotnetcore/NPOI#29]
Hello,

It is almost simular to this issue: 
https://github.com/dotnetcore/NPOI/issues/20
However, Aspose.Words (or Apose.Cells) or any other lib that I try to add to my project (with nuget manager) fails to install since I was using .NET Core 1.x. Now I updated to .NET core 2.x and now nuget allows me to install them but now I get the exception:

System.TypeLoadException: 'Could not load type 'System.Drawing.FontStyle' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'

When the debugger hits the line to convert.
I think this is because the nuget packages have dependencies on .NET 4.x and .NET core doesn t 'know' about them because .NET 4.X is not .NET Core.
Any solution for this you might think of?
Any help would be much appreciated since I searched on many places already.

Thanks in advance!

**Comment by yuleyule66** [comment]
In my experience, there is no way to solve the problem at present in .net core, because .net core are not fully support System.Drawing now.

**Comment by MaximCrabbe** [comment]
Ah that explains it. There is no roadmap right now as far as I was able to find that says that .net core will support System.drawing in the near future. That is kinda sad I ll guess I ll have to create a .net oldschool microservice to convert them which will be a pain in the *** since Filetransfers over HTTP never seems to go smooth (not perfomancewise but programming wise.) 
Thanks for the info anyway!
