### ISSUE TITLE
[XSSF] sheet.GetRow() method returns null

### ISSUE THREAD

**Issue by anagirnyak** [dotnetcore/NPOI#31]
I want to get row by sheet.GetRow(i) method invoke:
`for (int i = 0; i < sheet.LastRowNum; i++)`
        `{`
`                var currentRow = sheet.GetRow(i);`
`                //currentRow == null `
`               //sheet.LastRowNum > actual rows in excel `
        `}`
`}`

**Comment by baiyunchen** [comment]
if possible,provider you excel file.

**Comment by yuleyule66** [comment]
If there are any questions, please reopen this issue
