### ISSUE TITLE
Write to an existing excel file, while retaining it's formatting

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [dotnetcore/NPOI#33]
Please how may we write to an existing excel file, while retaining it's formatting?

For example, say i have a `template.xlsx`, which holds all the structure and formatting required.

I make a copy of this file, then attempt to fill the new file with new data.

The process completes without errors, but I cannot see any changes to the new file.

The gist below shows my attempt.

https://gist.github.com/CharlesOkwuagwu/a9a34647070b87a86a170875a8468ced

Kindly help point out what i'm getting wrong.

Thanks.

**Comment by yuleyule66** [comment]
@baiyunchen 
Hi, yunchen
I'm on a business trip recently. Can you see what the problem is?

**Comment by baiyunchen** [comment]
@CharlesOkwuagwu  
On new XSSFWorkbook(),NOPI.Core has some bugs(NPOI has the same problem) and it will close the stream,but I do not currently know how to fix it.
But for your current logic,you can rewrite the flowing code,I simply tested,it can run perfectly.
```
public void WriteExcel()
{
    string outputFileName = $@"xxx\template-{DateTime.Now.Ticks.ToString()}.xlsx";
    using (var templateStream =new FileStream(@"xxx\template.xlsx", FileMode.Open, FileAccess.Read))
    {
        var excel = new XSSFWorkbook(templateStream);
        var cell = excel.GetSheetAt(0).GetRow(2).GetCell(2);
        cell.SetCellValue("Issue 33");

        using (var outputStream = new FileStream(outputFileName, FileMode.Create, FileAccess.Write))
        {
            excel.Write(outputStream);
        }
    }
    using (var outputStream = File.OpenRead(outputFileName))
    {
        var excel = new XSSFWorkbook(outputStream);
        var cell = excel.GetSheetAt(0).GetRow(2).GetCell(2);
        Console.WriteLine(cell.ToString()); //here can console Issue 33
    }
}
```
Hope can help you !

**Comment by CharlesOkwuagwu** [comment]
thanks.
