### ISSUE TITLE
SheetUtil.CopyRow has bug

### ISSUE THREAD

**Issue by liningit** [dotnetcore/NPOI#40]
in SheetUtil row 186
`            IRow newRow = sheet.GetRow(targetRowIndex);
            IRow sourceRow = sheet.GetRow(sourceRowIndex);

            // If the row exist in destination, push down all rows by 1 else create a new row
            if (newRow != null)
            {
                sheet.ShiftRows(targetRowIndex, sheet.LastRowNum, 1);
            }
            else
            {
                newRow = sheet.CreateRow(targetRowIndex);
            }`
Should be
` if (newRow != null)
            {

                sheet.ShiftRows(targetRowIndex, sheet.LastRowNum, 1);

                newRow = sheet.GetRow(targetRowIndex);
            }`

**Comment by liningit** [comment]
Should be
    if (newRow != null)
        {
            sheet.ShiftRows(targetRowIndex, sheet.LastRowNum, 1);
        }`
   newRow = sheet.CreateRow(targetRowIndex);

**Comment by yuleyule66** [comment]
Fixed in v1.2.0
