### ISSUE TITLE
Error Getting with NuGet

### ISSUE THREAD

**Issue by bjstigall** [dotnetcore/NPOI#42]
when i get the package with NuGet (Install-Package DotNetCore.NPOI) i receive the error: 

Attempting to gather dependency information for package 'DotNetCore.NPOI.1.0.2' with respect to project 'GetForecastEngine', targeting '.NETFramework,Version=v4.7'
Gathering dependency information took 531.82 ms
Attempting to resolve dependencies for package 'DotNetCore.NPOI.1.0.2' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'SharpZipLib 0.86.0' is not compatible with 'DotNetCore.NPOI 1.0.2 constraint: SharpZipLib (>= 1.0.0-alpha2)'.

**Comment by yuleyule66** [comment]
This version of NPOI not support .NET Framework , only .NET Core. 

If you want to using NPOI in .NET Framework, You can use this: [https://github.com/tonyqus/npoi](https://github.com/tonyqus/npoi)

**Comment by mr0fka** [comment]
So if this version of NPOI not support .NET Framework why did you create .NET Standard 2.0 project?
You should target to .NET Core 2.0 instead of .NET Standard 2.0!
