### ISSUE TITLE
建议使用System.Drawing.Common替换ZKWeb.System.Drawing

### ISSUE THREAD

**Issue by csurn** [dotnetcore/NPOI#44]

**Comment by yuleyule66** [comment]
System.Drawing.Common API不够，有缺失

**Comment by csurn** [comment]
不了解楼上所说的System.Drawing.Common的API缺失是是针对哪个版本的。我这几天有个部署在cengos 7上的项目升级.net core 2.0时使用ZKWeb.System.Drawing的验证码不好用了，不修改代码的情况下替换成System.Drawing.Common 4.5.0-preview1-25914-04恢复正常。希望和建议日后如果System.Drawing.Common可以满足需求时进行替换。
