### ISSUE TITLE
貌似没有实现SXSSFWorkbook这个类

### ISSUE THREAD

**Issue by SayHelloXXXX** [dotnetcore/NPOI#45]
这是poi针对大数据量导出优化的类 HSSFWorkbook虽然省内存但是有6w行限制 XSSFWorkbook又太占内存 之前在.net framework上做的项目想移植下 看到npoi有core版很高兴 但是今天一看发现并没有SXSSFWorkbook这个类 不知道大牛可以实现不

**Comment by yuleyule66** [comment]
NPOI Core 只是做移植，并没有计划做新功能开发，如果你有兴趣，可以提交PR, 感谢对本项目的关注

**Comment by SayHelloXXXX** [comment]
这不是新功能 原来npoi就有的

**Comment by SayHelloXXXX** [comment]
SXSSFWorkbook在原来的npoi的 NPOI.XSSF.Streaming 这个命名空间下
