### ISSUE TITLE
CopyRow Bug

### ISSUE THREAD

**Issue by lirushi** [dotnetcore/NPOI#59]
NPOI.SS.Util.SheetUtil In line 183
If there is a row in the target location, only the target row and the bottom row are moved, a new row is not created at the target location, and then the row that was originally at the target location is returned, resulting in an operation row error.I think **createtRow**  should be placed outside the **else**.
如果目标位置存在行的话就只会将目标行及下面的行移动，而不会在目标位置创建新行，然后返回的是原本在目标位置的行，导致操作行错误。我觉得应该将createtRow放到else外面。

**Comment by yuleyule66** [comment]
Fixed in v1.2.0
