### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by AmbroiseCouissin** [dotnetcore/NPOI#69]
Hi there :)

More and more people are using Alpine and sdk-alpine/aspnetcore-runtime-alpine images.

In order to make this work, I believe we need to add this int the dockerfile right?:
```
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk --update add libgdiplus
```

Maybe it's something we should add on the readme file.

**Comment by yuleyule66** [comment]
Thanks for your feedback, it sounds good, and I'll update it to readme file later!
