### ISSUE TITLE
AutoSizeColumn is not working properly

### ISSUE THREAD

**Issue by ivansoriabia** [dotnetcore/NPOI#77]
Hello!

I am having some troubles with the function Sheet.AutoSizeColumn because it doesn't set column with properly. It cuts text.

There is a way that AutoSizeColumn don't cut the text?

In the photo that I have send you, you will able to see what I am asking you.

![autocolumnsize cuts text](https://user-images.githubusercontent.com/33115120/43892438-33a71158-9bcc-11e8-8b55-1efb6452b2d9.PNG)

**Comment by randalvance** [comment]
Same issue, it seems the column is resizing but not up to an extent that all the column contents are shown entirely.

**Comment by tonyqus** [comment]
The migration of TextRenderer is totally wrong. He doesn't understand how MeasureText method really works. 

Please check https://github.com/dotnetcore/NPOI/blob/master/src/NPOI/TextRenderer.cs

**Comment by gtbuchanan** [comment]
To be clear, AutoSizeColumn is still a little off on netstandard after my fix but it's much better than it was before.

I'll see if I'm able to submit a better fix for netstandard at a later time.
